name: update npm

on:
    release:
        types: [created]

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  node-version: "18.x"
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm run build
            - name: Publish package to NPM
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
